language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer self-update
  - composer install --no-progress --prefer-source
  - npm install -g jscs
  - npm install -g jshint

script:
  - jshint src
  - jscs src
  - find src \( -name '*.php' \) -exec php -lf {} \;
  - phpunit
